### ISSUE TITLE
Issue with prefix_list_detailed

### ISSUE THREAD

**Issue by mahin287** [automateyournetwork/ACEye#137]
Please find the error details given below.

No prefix lists
Traceback (most recent call last):
  File "/home/mayin/projects/python/ACEye/aceyecode/src/aceye/aceye.py", line 6563, in <module>
    cli()
  File "/home/mayin/projects/python/ACEye/ACI/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/mayin/projects/python/ACEye/ACI/lib/python3.10/site-packages/rich_click/rich_command.py", line 19, in main
    rv = super().main(*args, standalone_mode=False, **kwargs)
  File "/home/mayin/projects/python/ACEye/ACI/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/mayin/projects/python/ACEye/ACI/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mayin/projects/python/ACEye/ACI/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/mayin/projects/python/ACEye/aceyecode/src/aceye/aceye.py", line 6560, in cli
    invoke_class.aceye()
  File "/home/mayin/projects/python/ACEye/aceyecode/src/aceye/aceye.py", line 27, in aceye
    asyncio.run(self.main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/mayin/projects/python/ACEye/aceyecode/src/aceye/aceye.py", line 576, in main
    await self.all_files(json.dumps(results, indent=4, sort_keys=True))        
  File "/home/mayin/projects/python/ACEye/aceyecode/src/aceye/aceye.py", line 6543, in all_files
    await asyncio.gather(self.json_file(parsed_json), self.yaml_file(parsed_json), self.csv_file(parsed_json), self.markdown_file(parsed_json), self.html_file(parsed_json), self.mindmap_file(parsed_json))
  File "/home/mayin/projects/python/ACEye/aceyecode/src/aceye/aceye.py", line 659, in json_file
    await f.write(json.dumps(payload['imdata'], indent=4, sort_keys=True))
TypeError: list indices must be integers or slices, not str

**Comment by JT252** [comment]
What version is your APIC?

**Comment by mahin287** [comment]
Cisco always on sandbox which is 6.0(2h).
