### ISSUE TITLE
ACEye crashed

### ISSUE THREAD

**Issue by jagz70** [automateyournetwork/ACEye#141]
Hello John,

I am a fun of your youtube content and I got the following errors when I tried to use the ACEye tool.  Any help will be appreciate it.  

Traceback (most recent call last):
  File "/Users/jgarci/Desktop/NetDevOps-Automation/aceye/venv/bin/aceye", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/Users/jgarci/Desktop/NetDevOps-Automation/aceye/venv/lib/python3.11/site-packages/aceye/script.py", line 3, in run
    cli()
  File "/Users/jgarci/Desktop/NetDevOps-Automation/aceye/venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jgarci/Desktop/NetDevOps-Automation/aceye/venv/lib/python3.11/site-packages/rich_click/rich_command.py", line 152, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/jgarci/Desktop/NetDevOps-Automation/aceye/venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jgarci/Desktop/NetDevOps-Automation/aceye/venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jgarci/Desktop/NetDevOps-Automation/aceye/venv/lib/python3.11/site-packages/aceye/aceye.py", line 6546, in cli
    invoke_class.aceye()
  File "/Users/jgarci/Desktop/NetDevOps-Automation/aceye/venv/lib/python3.11/site-packages/aceye/aceye.py", line 27, in aceye
    asyncio.run(self.main())
  File "/usr/local/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/jgarci/Desktop/NetDevOps-Automation/aceye/venv/lib/python3.11/site-packages/aceye/aceye.py", line 556, in main
    await self.all_files(json.dumps(results, indent=4, sort_keys=True))
  File "/Users/jgarci/Desktop/NetDevOps-Automation/aceye/venv/lib/python3.11/site-packages/aceye/aceye.py", line 6529, in all_files
    await asyncio.gather(self.json_file(parsed_json), self.yaml_file(parsed_json), self.csv_file(parsed_json), self.markdown_file(parsed_json), self.html_file(parsed_json), self.mindmap_file(parsed_json))
  File "/Users/jgarci/Desktop/NetDevOps-Automation/aceye/venv/lib/python3.11/site-packages/aceye/aceye.py", line 3585, in markdown_file
    markdown_output = await markdown_template.render_async(api = api,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jgarci/Desktop/NetDevOps-Automation/aceye/venv/lib/python3.11/site-packages/jinja2/environment.py", line 1327, in render_async
    return self.environment.handle_exception()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jgarci/Desktop/NetDevOps-Automation/aceye/venv/lib/python3.11/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/jgarci/Desktop/NetDevOps-Automation/aceye/venv/lib/python3.11/site-packages/jinja2/environment.py", line 1324, in <listcomp>
    [n async for n in self.root_render_func(ctx)]  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jgarci/Desktop/NetDevOps-Automation/aceye/venv/lib/python3.11/site-packages/aceye/aci_markdown.j2", line 1398, in top-level template code
    | {{ nexthop.uribv4Nexthop.attributes.name }} | {{ nexthop.uribv4Nexthop.attributes.Nhmetric }} | {{ nexthop.uribv4Nexthop.attributes.Nhtag }} | {{ nexthop.uribv4Nexthop.attributes.active }} | {{ nexthop.uribv4Nexthop.attributes.addr }} | {{ nexthop.uribv4Nexthop.attributes.childAction }} | {{ nexthop.uribv4Nexthop.attributes.createTs }} | {{ nexthop.uribv4Nexthop.attributes.dn }} | {{ nexthop.uribv4Nexthop.attributes.if }} | {{ nexthop.uribv4Nexthop.attributes.metric }} | {{ nexthop.uribv4Nexthop.attributes.modTs }} | {{ nexthop.uribv4Nexthop.attributes.owner }} | {{ nexthop.uribv4Nexthop.attributes.pref }} | {{ nexthop.uribv4Nexthop.attributes.routeType }} | {{ nexthop.uribv4Nexthop.attributes.rwVnid }} | {{ nexthop.uribv4Nexthop.attributes.status }} | {{ nexthop.uribv4Nexthop.attributes.tag }} | {{ nexthop.uribv4Nexthop.attributes.type }} | {{ nexthop.uribv4Nexthop.attributes.vrf }} |
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jgarci/Desktop/NetDevOps-Automation/aceye/venv/lib/python3.11/site-packages/jinja2/environment.py", line 487, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'uribv4Nexthop'

**Comment by automateyournetwork** [comment]
Thanks ! Looks like a next hop issue

Automation/aceye/venv/lib/python3.11/site-packages/jinja2/environment.py",
line 487, in getattr
return getattr(obj, attribute)
^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'dict object' has no attribute
'uribv4Nexthop'
You might be able to comment out this particular parser if you have no next
hops

Hope this helps and thanks for the kind words and support

John
